name: Commit style

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'dev/*'

jobs:
  check-commit-style:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: croct-tech/opinionated-commit-message@master
        with:
          allow-one-liners: 'true'
          skip-body-check: 'true'
